version: 3
exfil:
  list:
    default-chrome:
      events:
      - CONNECTED
      - DNS_REQUEST
      - HISTORY_DUMP_REP
      - HTTP_REQUEST
      - OS_PACKAGES_REP
      - RECEIPT
      platforms:
      - chrome
      tags: []
    default-linux:
      events:
      - AUTORUN_CHANGE
      - CODE_IDENTITY
      - CONNECTED
      - DIR_FINDHASH_REP
      - DIR_LIST_REP
      - DNS_REQUEST
      - DRIVER_CHANGE
      - EXEC_OOB
      - EXISTING_PROCESS
      - FILE_DEL_REP
      - FILE_GET_REP
      - FILE_HASH_REP
      - FILE_INFO_REP
      - FILE_MOV_REP
      - FILE_TYPE_ACCESSED
      - FIM_HIT
      - FIM_LIST_REP
      - GET_DOCUMENT_REP
      - GET_EXFIL_EVENT_REP
      - HIDDEN_MODULE_DETECTED
      - HISTORY_DUMP_REP
      - LOG_GET_REP
      - LOG_LIST_REP
      - MEM_FIND_HANDLE_REP
      - MEM_FIND_STRING_REP
      - MEM_HANDLES_REP
      - MEM_MAP_REP
      - MEM_READ_REP
      - MEM_STRINGS_REP
      - MODULE_MEM_DISK_MISMATCH
      - NETSTAT_REP
      - NETWORK_CONNECTIONS
      - NETWORK_SUMMARY
      - NEW_DOCUMENT
      - NEW_PROCESS
      - OS_AUTORUNS_REP
      - OS_DRIVERS_REP
      - OS_KILL_PROCESS_REP
      - OS_PACKAGES_REP
      - OS_PROCESSES_REP
      - OS_RESUME_REP
      - OS_SERVICES_REP
      - OS_SUSPEND_REP
      - OS_VERSION_REP
      - PCAP_LIST_INTERFACES_REP
      - POSSIBLE_DOC_EXPLOIT
      - RECEIPT
      - RECON_BURST
      - SELF_TEST_RESULT
      - SENSITIVE_PROCESS_ACCESS
      - SERVICE_CHANGE
      - TERMINATE_PROCESS
      - THREAD_INJECTION
      - USER_OBSERVED
      - VOLUME_MOUNT
      - VOLUME_UNMOUNT
      - YARA_DETECTION
      platforms:
      - linux
      tags: []
    default-macos:
      events:
      - NEW_PROCESS
      - TERMINATE_PROCESS
      - CODE_IDENTITY
      - DNS_REQUEST
      - HIDDEN_MODULE_DETECTED
      - NETWORK_SUMMARY
      - FILE_GET_REP
      - FILE_DEL_REP
      - FILE_MOV_REP
      - FILE_HASH_REP
      - FILE_INFO_REP
      - DIR_LIST_REP
      - MEM_MAP_REP
      - MEM_READ_REP
      - MEM_HANDLES_REP
      - MEM_FIND_HANDLE_REP
      - MEM_STRINGS_REP
      - MEM_FIND_STRING_REP
      - OS_SERVICES_REP
      - OS_DRIVERS_REP
      - OS_KILL_PROCESS_REP
      - OS_SUSPEND_REP
      - OS_RESUME_REP
      - OS_PROCESSES_REP
      - OS_AUTORUNS_REP
      - EXEC_OOB
      - GET_EXFIL_EVENT_REP
      - MODULE_MEM_DISK_MISMATCH
      - YARA_DETECTION
      - SERVICE_CHANGE
      - DRIVER_CHANGE
      - AUTORUN_CHANGE
      - NEW_DOCUMENT
      - GET_DOCUMENT_REP
      - VOLUME_MOUNT
      - VOLUME_UNMOUNT
      - RECON_BURST
      - POSSIBLE_DOC_EXPLOIT
      - HISTORY_DUMP_REP
      - USER_OBSERVED
      - FILE_TYPE_ACCESSED
      - EXISTING_PROCESS
      - SELF_TEST_RESULT
      - RECEIPT
      - OS_VERSION_REP
      - CONNECTED
      - OS_PACKAGES_REP
      - DIR_FINDHASH_REP
      - FIM_HIT
      - FIM_LIST_REP
      - NETSTAT_REP
      - THREAD_INJECTION
      - SENSITIVE_PROCESS_ACCESS
      - LOG_GET_REP
      - LOG_LIST_REP
      platforms:
      - mac
      tags: []
    default-windows:
      events:
      - AUTORUN_CHANGE
      - CODE_IDENTITY
      - CONNECTED
      - DIR_FINDHASH_REP
      - DIR_LIST_REP
      - DNS_REQUEST
      - DRIVER_CHANGE
      - EXEC_OOB
      - EXISTING_PROCESS
      - FILE_DEL_REP
      - FILE_GET_REP
      - FILE_HASH_REP
      - FILE_INFO_REP
      - FILE_MOV_REP
      - FILE_TYPE_ACCESSED
      - FIM_HIT
      - FIM_LIST_REP
      - GET_DOCUMENT_REP
      - GET_EXFIL_EVENT_REP
      - HIDDEN_MODULE_DETECTED
      - HISTORY_DUMP_REP
      - LOG_GET_REP
      - LOG_LIST_REP
      - MEM_FIND_HANDLE_REP
      - MEM_FIND_STRING_REP
      - MEM_HANDLES_REP
      - MEM_MAP_REP
      - MEM_READ_REP
      - MEM_STRINGS_REP
      - MODULE_MEM_DISK_MISMATCH
      - NETSTAT_REP
      - NETWORK_CONNECTIONS
      - NETWORK_SUMMARY
      - NEW_DOCUMENT
      - NEW_PROCESS
      - OS_AUTORUNS_REP
      - OS_DRIVERS_REP
      - OS_KILL_PROCESS_REP
      - OS_PACKAGES_REP
      - OS_PROCESSES_REP
      - OS_RESUME_REP
      - OS_SERVICES_REP
      - OS_SUSPEND_REP
      - OS_VERSION_REP
      - POSSIBLE_DOC_EXPLOIT
      - RECEIPT
      - RECON_BURST
      - REGISTRY_LIST_REP
      - SELF_TEST_RESULT
      - SENSITIVE_PROCESS_ACCESS
      - SERVICE_CHANGE
      - TERMINATE_PROCESS
      - THREAD_INJECTION
      - USER_OBSERVED
      - VOLUME_MOUNT
      - VOLUME_UNMOUNT
      - YARA_DETECTION
      platforms:
      - windows
      tags: []
  perf: {}
  watch: {}