version: 3
hives:
  fp:
    WMI Event Subscription:
      data:
        op: and
        rules:
        - op: is
          path: cat
          value: WMI Event Subscription
        - op: is
          path: detect/Event/System/Execution/ProcessID
          value: '4'
      usr_mtd:
        enabled: true
        expiry: 0
        tags: []